beianInfo:
  - title: "未ICP备0000000000号"
    href: "http://beian.miit.gov.cn/"
    target: "_blank"
    type: "link"
beianInfo2:
  - title: "未公网安备000000000000号"
    href: "http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=00000000000000"
    target: "_blank"
    type: "link"